version: '3'

services:

  nginx:
    container_name: nginx_container
    image: nginx:1.15.6
    ports:
      - '80:80'
    depends_on:
      - php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: "Asia/Tokyo"

  php:
    container_name: php_container
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis

  db:
    container_name: db_container
    image: mysql:8.0.28
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSROOT}

  redis:
    container_name: redis_container
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/data
    command: redis-server --appendonly yes

volumes:
  db-data:

